#!/bin/bash
#ver. 4
##this script will check mysql and apache
##if that service is not running
##it will start the service and send an email to you
##if the restart does not work, it sends an email and then exits

## uses Gmail SMTP, so your username/email and password should be for a Gmail-hosted account
## requires mailx to be installed on the server (sudo apt-get install heirloom-mailx)

## set the path ##this works for Ubuntu 14.04 and 16.04
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

## set email address to receive the message
TO_EMAIL="you@example.com"

## set SMTP authentication and name
SMTP_EMAIL="someone@domain.com"
SMTP_NICENAME="John Smith"
SMTP_PASSWORD="abcde12345"

## list your services you want to check
SERVICES=( 'apache2' 'mysql' )

#### OK. STOP EDITING ####


 for i in "${SERVICES[@]}"
  do
 ###CHECK SERVICE####
 `pgrep $i >/dev/null 2>&1`
 STATS=$(echo $?)

 ###IF SERVICE IS NOT RUNNING####
 if [[  $STATS == 1  ]]

  then
  ##TRY TO RESTART THAT SERVICE###
  service $i start

  ##CHECK IF RESTART WORKED###
  `pgrep $i >/dev/null 2>&1`
  RESTART=$(echo $?)

  if [[  $RESTART == 0  ]]
   ##IF SERVICE HAS BEEN RESTARTED###
   then

    ##REMOVE THE TMP FILE IF EXISTS###
    if [ -f "/tmp/$i" ];
    then
     rm /tmp/$i
    fi

    ##SEND AN EMAIL###
    MESSAGE="$i was down, but I was able to restart it on $(hostname) $(date)"
    SUBJECT="$i was down but restarted on $(hostname) $(date)"
    echo $MESSAGE | mailx -s "$SUBJECT" -S smtp-use-starttls -S ssl-verify=ignore -S smtp-auth=login -S smtp=smtp://smtp.gmail.com:587 -S from="$SMTP_EMAIL($SMTP_NICENAME)" -S smtp-auth-user=$SMTP_EMAIL -S smtp-auth-password=$SMTP_PASSWORD -S ssl-verify=ignore $TO_EMAIL

   else
    ##IF RESTART DID NOT WORK###

    ##CHECK IF THERE IS NOT A TMP FILE###
    if [ ! -f "/tmp/$i" ]; then

     ##CREATE A TMP FILE###
     touch /tmp/$i

     ##SEND A DIFFERENT EMAIL###
     MESSAGE="$i is down on $(hostname) at $(date) (restart failed)"
     SUBJECT=" $i is down on $(hostname) $(date)"
     echo $MESSAGE | mailx -s "$SUBJECT" -S smtp-use-starttls -S ssl-verify=ignore -S smtp-auth=login -S smtp=smtp://smtp.gmail.com:587 -S from="$SMTP_EMAIL($SMTP_NICENAME)"
 -S smtp-auth-user=$SMTP_EMAIL -S smtp-auth-password=$SMTP_PASSWORD -S ssl-verify=igno
re $TO_EMAIL
    fi
  fi
 fi



  done
exit 0;